### PR TITLE
Add a binary shim to avoid macOS Cython errors (and likely others)

### LINKED ISSUE #64: Use symlink instead of nesting scripts for BUILD_PREFIX/bin/python
In https://github.com/conda-forge/tensorflow-feedstock/pull/286#issuecomment-1360865890 @pkgw found that nesting scripts isn't really ideal for OSX:

> My testing indicates that on Linux, you can "nest" shebang scripts in this way and the sensible thing will happen, but on OSX it appears that is not the case. See [this StackOverflow Q&A](https://stackoverflow.com/questions/25894895/why-does-osx-require-shebang-interpreters-to-be-binaries).

https://github.com/conda-forge/cross-python-feedstock/blob/c356bb3a8fc9d98bf6fa8ae6c4fe3ca8e33ec9d6/recipe/activate-cross-python.sh#L53-L54

Could we make this a symlink instead?

### PR DESCRIPTION
**Pull request by pkgw**
This closes #64, hopefully. As documented in the PR comments, on macOS we can't just symlink or make a wrapper script to the cross-python launcher because then the resulting `python` can't be used in the shebang line of other scripts. It has to be a binary. So, I wrote a little Rust program that has the same effect. Took several tries to get it to work right in the face of how the prefix-rewriting is handled, but I can confirm that it helps get conda-forge/tensorflow-feedstock#286 past the initial build issues.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pkgw** [comment]
@ngam OK, done.

**Comment by h-vetinari** [comment]
The artefacts get uploaded correctly, and are listed and selectable, but downloading fails - never seen that before

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please restart ci

**Comment by h-vetinari** [comment]
Still not working. Looks like an azure issue TBH, because the artefacts get uploaded correctly...

**Comment by pkgw** [comment]
@isuruf What do you think of this PR, modulo the Azure artifacts issues?

**Comment by erykoff** [comment]
I can't tell if I'm hitting this error or something else with `f2py`, but I think it's important to get this merged.  What's the current status?

**Comment by isuruf** [comment]
I'm supportive of this PR, but I'm not really comfortable with using rust for this and introducing a heavy dependency like rust early in the stack.

**Comment by pkgw** [comment]
Personally, I want to avoid writing new C/C++ as much as I possibly can, and want to push towards a world where we use Rust for these kinds of systems-level tasks as much as possible. I also expect that we'll be seeing Rust more and more early in the dependency stack (Rust in the Linux kernel, etc.), and think that with the general shift in that direction, issues with bootstrapping are unlikely to arise.

That being said, it's clearly true that in practice the C/C++ toolchain is more "foundational" than Rust right now, and the binary tool here could definitely be done in C. I would rather not rewrite it in C without a specific reason requiring that, but that's a matter of my preferences rather than a technical argument.

**Comment by isuruf** [comment]
The issue is that my rust knowledge is rusty (:smile:) and I don't want to take on the burden of maintaining a rust code base whereas I feel comfortable with C/C++.

**Comment by pkgw** [comment]
I can definitely say that I'll be happy to help work through any issues that may arise, although this program is simple enough that I certainly *hope* that won't need much in the way of maintenance. Anything else I can do that will help you feel better about the maintenance burden?

**Comment by pkgw** [comment]
Superseded by #66!

**Pull request closed without merging**
