### PR TITLE
Add Python3.12 migration

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Usually this does not work for a new python release and needs some patches. Did you check that this works?

**Comment by pavelzw** [comment]
I haven't tested it out (except for the tests defined in the `meta.yaml`). But AFAICS, #56 also didn't apply extra patches?
If you want some more tests, I can try to test it tomorrow on another feedstock.

**Comment by isuruf** [comment]
> But AFAICS, https://github.com/conda-forge/cross-python-feedstock/pull/56 also didn't apply extra patches?

There were a couple of patches as a follow-up. Don't want to repeat the same mistakes.

**Comment by pavelzw** [comment]
In https://github.com/conda-forge/black-feedstock/pull/73 everything seems to be working.

I'm trying https://github.com/conda-forge/maturin-feedstock/pull/105 and pydantic-core now...

**Comment by pavelzw** [comment]
@isuruf all three tests went fine AFAICS. With the pydantic-core PR, we should have covered at least a part of the PyO3 stuff from the activation scripts...
Are these enough tests?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
