### PR TITLE
add pypy 3.8/3.9

### LINKED ISSUE #41: Adding PyPy 3.8 & 3.9 builds for ARM & Power
Would it be possible to add PyPy 3.8 & 3.9 builds for ARM & Power? If not, would it make sense to exclude these from migration somehow? Seems some CI builds are added that look for these ( https://github.com/conda-forge/setuptools-feedstock/pull/252 )

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #41

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
CC @isuruf @jakirkham @mattip

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Thanks

**Comment by mattip** [comment]
Is this connected to the failure of conda-forge/postgresql-feedstock#122 with the error 
> package cross-python_linux-aarch64-3.10-13_cpython requires python 3.10.* *_cpython, but none of the providers can be installed

If so, would re-rendering that PR clear the problem?

**Comment by isuruf** [comment]
Yes, restarting CI would fix it, but wait 1-2 hours for the package to appear on the CDN

**Pull request merged**
